# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BOOT_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BootButton = QtWidgets.QPushButton(self.centralwidget)
        self.BootButton.setGeometry(QtCore.QRect(30, 465, 636, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BootButton.setFont(font)
        self.BootButton.setObjectName("BootButton")
        self.GenProcess = QtWidgets.QProgressBar(self.centralwidget)
        self.GenProcess.setGeometry(QtCore.QRect(30, 515, 636, 21))
        self.GenProcess.setProperty("value", 0)
        self.GenProcess.setObjectName("GenProcess")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 430, 431, 31))
        self.textEdit.setObjectName("textEdit")
        self.BrowseHexFile = QtWidgets.QToolButton(self.centralwidget)
        self.BrowseHexFile.setGeometry(QtCore.QRect(465, 430, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BrowseHexFile.setFont(font)
        self.BrowseHexFile.setObjectName("BrowseHexFile")
        self.StartFrame = QtWidgets.QTextEdit(self.centralwidget)
        self.StartFrame.setGeometry(QtCore.QRect(420, 286, 246, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StartFrame.setFont(font)
        self.StartFrame.setObjectName("StartFrame")
        self.EndFrame = QtWidgets.QTextEdit(self.centralwidget)
        self.EndFrame.setGeometry(QtCore.QRect(420, 377, 246, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.EndFrame.setFont(font)
        self.EndFrame.setObjectName("EndFrame")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(420, 241, 246, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(420, 332, 246, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.SectorList = QtWidgets.QListWidget(self.centralwidget)
        self.SectorList.setGeometry(QtCore.QRect(30, 130, 371, 291))
        self.SectorList.setObjectName("SectorList")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SectorList.addItem(item)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 50, 371, 76))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.checkFrameEn = QtWidgets.QCheckBox(self.centralwidget)
        self.checkFrameEn.setGeometry(QtCore.QRect(420, 195, 246, 46))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkFrameEn.setFont(font)
        self.checkFrameEn.setObjectName("checkFrameEn")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(420, 80, 246, 41))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.StartAddress = QtWidgets.QTextEdit(self.centralwidget)
        self.StartAddress.setGeometry(QtCore.QRect(420, 125, 246, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StartAddress.setFont(font)
        self.StartAddress.setObjectName("StartAddress")
        self.checkStartAddrEn = QtWidgets.QCheckBox(self.centralwidget)
        self.checkStartAddrEn.setGeometry(QtCore.QRect(420, 40, 241, 46))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkStartAddrEn.setFont(font)
        self.checkStartAddrEn.setChecked(True)
        self.checkStartAddrEn.setObjectName("checkStartAddrEn")
        self.comboComPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboComPort.setGeometry(QtCore.QRect(865, 155, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboComPort.setFont(font)
        self.comboComPort.setIconSize(QtCore.QSize(22, 20))
        self.comboComPort.setObjectName("comboComPort")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboComPort.addItem("")
        self.comboBaud = QtWidgets.QComboBox(self.centralwidget)
        self.comboBaud.setGeometry(QtCore.QRect(865, 255, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBaud.setFont(font)
        self.comboBaud.setIconSize(QtCore.QSize(22, 20))
        self.comboBaud.setObjectName("comboBaud")
        self.comboBaud.addItem("")
        self.comboBaud.addItem("")
        self.comboBaud.addItem("")
        self.comboBaud.addItem("")
        self.comboBaud.addItem("")
        self.comboBaud.addItem("")
        self.comboStopBits = QtWidgets.QComboBox(self.centralwidget)
        self.comboStopBits.setGeometry(QtCore.QRect(865, 305, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboStopBits.setFont(font)
        self.comboStopBits.setIconSize(QtCore.QSize(22, 20))
        self.comboStopBits.setObjectName("comboStopBits")
        self.comboStopBits.addItem("")
        self.comboStopBits.addItem("")
        self.comboStopBits.addItem("")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(710, 155, 146, 41))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(710, 255, 146, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(710, 305, 146, 41))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(710, 355, 146, 41))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.comboParity = QtWidgets.QComboBox(self.centralwidget)
        self.comboParity.setGeometry(QtCore.QRect(865, 355, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboParity.setFont(font)
        self.comboParity.setIconSize(QtCore.QSize(22, 20))
        self.comboParity.setObjectName("comboParity")
        self.comboParity.addItem("")
        self.comboParity.addItem("")
        self.comboParity.addItem("")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(710, 405, 146, 41))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.TimeoutText = QtWidgets.QTextEdit(self.centralwidget)
        self.TimeoutText.setGeometry(QtCore.QRect(865, 405, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.TimeoutText.setFont(font)
        self.TimeoutText.setObjectName("TimeoutText")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(695, 55, 291, 81))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(695, 140, 291, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(710, 205, 146, 41))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.comboDataSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboDataSize.setGeometry(QtCore.QRect(865, 205, 106, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboDataSize.setFont(font)
        self.comboDataSize.setIconSize(QtCore.QSize(22, 20))
        self.comboDataSize.setObjectName("comboDataSize")
        self.comboDataSize.addItem("")
        self.comboDataSize.addItem("")
        self.comboDataSize.addItem("")
        self.SetConfigBTN = QtWidgets.QPushButton(self.centralwidget)
        self.SetConfigBTN.setGeometry(QtCore.QRect(695, 465, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SetConfigBTN.setFont(font)
        self.SetConfigBTN.setObjectName("SetConfigBTN")
        self.graphicsView.raise_()
        self.BootButton.raise_()
        self.GenProcess.raise_()
        self.textEdit.raise_()
        self.BrowseHexFile.raise_()
        self.StartFrame.raise_()
        self.EndFrame.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_4.raise_()
        self.SectorList.raise_()
        self.textBrowser_3.raise_()
        self.checkFrameEn.raise_()
        self.textBrowser_5.raise_()
        self.StartAddress.raise_()
        self.checkStartAddrEn.raise_()
        self.comboComPort.raise_()
        self.comboBaud.raise_()
        self.comboStopBits.raise_()
        self.textBrowser_6.raise_()
        self.textBrowser_7.raise_()
        self.textBrowser_8.raise_()
        self.textBrowser_9.raise_()
        self.comboParity.raise_()
        self.textBrowser_10.raise_()
        self.TimeoutText.raise_()
        self.textBrowser_11.raise_()
        self.textBrowser_12.raise_()
        self.comboDataSize.raise_()
        self.SetConfigBTN.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BootButton.setText(_translate("MainWindow", "Boot Firmware"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BrowseHexFile.setText(_translate("MainWindow", "Browse Hex File"))
        self.StartFrame.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.EndFrame.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Start Frame</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">End Frame</span></p></body></html>"))
        __sortingEnabled = self.SectorList.isSortingEnabled()
        self.SectorList.setSortingEnabled(False)
        item = self.SectorList.item(0)
        item.setText(_translate("MainWindow", "Sector 0 : 0x0800.0000 - 0x0800.3FFF"))
        item = self.SectorList.item(1)
        item.setText(_translate("MainWindow", "Sector 1 : 0x0800.4000 - 0x0800.7FFF"))
        item = self.SectorList.item(2)
        item.setText(_translate("MainWindow", "Sector 2 : 0x0800.8000 - 0x0800.BFFF"))
        item = self.SectorList.item(3)
        item.setText(_translate("MainWindow", "Sector 3 : 0x0800.C000 - 0x0800.FFFF"))
        item = self.SectorList.item(4)
        item.setText(_translate("MainWindow", "Sector 4 : 0x0801.0000 - 0x0801.FFFF"))
        item = self.SectorList.item(5)
        item.setText(_translate("MainWindow", "Sector 5 : 0x0802.0000 - 0x0803.FFFF "))
        item = self.SectorList.item(6)
        item.setText(_translate("MainWindow", "Sector 6 : 0x0804.0000 - 0x0805.FFFF"))
        item = self.SectorList.item(7)
        item.setText(_translate("MainWindow", "Sector 7 : 0x0806.0000 - 0x0807.FFFF"))
        self.SectorList.setSortingEnabled(__sortingEnabled)
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Choose Sector to<br />Load Firmware </span></p></body></html>"))
        self.checkFrameEn.setText(_translate("MainWindow", "Start/End Frame Enable"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Start Address</span></p></body></html>"))
        self.StartAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.checkStartAddrEn.setText(_translate("MainWindow", "Start Address Enable"))
        self.comboComPort.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboComPort.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboComPort.setItemText(2, _translate("MainWindow", "COM3"))
        self.comboComPort.setItemText(3, _translate("MainWindow", "COM4"))
        self.comboComPort.setItemText(4, _translate("MainWindow", "COM5"))
        self.comboComPort.setItemText(5, _translate("MainWindow", "COM6"))
        self.comboComPort.setItemText(6, _translate("MainWindow", "COM7"))
        self.comboComPort.setItemText(7, _translate("MainWindow", "COM8"))
        self.comboComPort.setItemText(8, _translate("MainWindow", "COM9"))
        self.comboComPort.setItemText(9, _translate("MainWindow", "COM10"))
        self.comboComPort.setItemText(10, _translate("MainWindow", "COM11"))
        self.comboComPort.setItemText(11, _translate("MainWindow", "COM12"))
        self.comboBaud.setCurrentText(_translate("MainWindow", "1200"))
        self.comboBaud.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBaud.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBaud.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBaud.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBaud.setItemText(4, _translate("MainWindow", "47600"))
        self.comboBaud.setItemText(5, _translate("MainWindow", "115200"))
        self.comboStopBits.setCurrentText(_translate("MainWindow", "0.5 bit"))
        self.comboStopBits.setItemText(0, _translate("MainWindow", "0.5 bit"))
        self.comboStopBits.setItemText(1, _translate("MainWindow", "1 bit"))
        self.comboStopBits.setItemText(2, _translate("MainWindow", "2 bit"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">COM Port</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Baudrate</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Stop Bits</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Parity Bit</span></p></body></html>"))
        self.comboParity.setItemText(0, _translate("MainWindow", "None"))
        self.comboParity.setItemText(1, _translate("MainWindow", "Odd"))
        self.comboParity.setItemText(2, _translate("MainWindow", "Even"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Timeout</span></p></body></html>"))
        self.TimeoutText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#55aa00;\">Serial<br />Configuration</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">DataSize</span></p></body></html>"))
        self.comboDataSize.setItemText(0, _translate("MainWindow", "8"))
        self.comboDataSize.setItemText(1, _translate("MainWindow", "9"))
        self.comboDataSize.setItemText(2, _translate("MainWindow", "10"))
        self.SetConfigBTN.setText(_translate("MainWindow", "Set Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
